pr: silver-zone to sprint-3
iNineBD/DataFlowServer-3Sem2024 pull request #24
Opened 2024-05-11 14:27 UTC by Andre-Bernardes200

2024-05-11 22:46 UTC, JoaoMatheusLamao requested changes

2024-05-11 22:46 UTC, JoaoMatheusLamao commented on api-domrock/src/main/java/com/dataflow/apidomrock/services/BronzeZoneService.java
> +                        logger.insert(user.get().getId(), arquivo.getId(), "O metadado " + metadataRepository.findById(idMetadado).get().getNome() + " foi inserido no hash", Estagio.B, Acao.INSERIR);
As operações "Optional.get()...." devem ter validações antes para evitarmos null pointers

![image](https://github.com/iNineBD/DataFlowServer-3Sem2024/assets/77554165/ef50f062-5ac7-47f4-8ed4-c25c421018fa)

2024-05-11 22:46 UTC, JoaoMatheusLamao commented on api-domrock/src/main/java/com/dataflow/apidomrock/services/SilverZoneService.java
> +    public void updateStatus (RequestBodySetStatusSz request) throws CustomException {
Anotar como operações transacionais, uma vez que há operações na base.

2024-05-12 02:12 UTC, Andre-Bernardes200 commented on api-domrock/src/main/java/com/dataflow/apidomrock/services/BronzeZoneService.java
> +                        logger.insert(user.get().getId(), arquivo.getId(), "O metadado " + metadataRepository.findById(idMetadado).get().getNome() + " foi inserido no hash", Estagio.B, Acao.INSERIR);
Resolvido

2024-05-12 02:12 UTC, Andre-Bernardes200 commented on api-domrock/src/main/java/com/dataflow/apidomrock/services/SilverZoneService.java
> +    public void updateStatus (RequestBodySetStatusSz request) throws CustomException {
Colocado a anotação transaction

2024-05-12 02:18 UTC, JoaoMatheusLamao approved these changes

2024-05-12 02:18 UTC, merged